### ISSUE TITLE
no longer works

### ISSUE THREAD

**Issue by Void48** [yakisova41/google-search-classic-navbar#6]

**Comment by yakisova41** [comment]
On all 7 Google accounts I own, the Google navbar is in the classic design without the need for this extension.
This is probably due to A/B testing by Google, but does anyone still have a Material v3 design navbar?

I can't reproduce it in my environment and therefore can't develop it any further 😥.

**Comment by Void48** [comment]
> On all 7 Google accounts I own, the Google navbar is in the classic design without the need for this extension. This is probably due to A/B testing by Google, but does anyone still have a Material v3 design navbar?
> 
> I can't reproduce it in my environment and therefore can't develop it any further 😥.

If you use the United States - English region/language do you get the new navbar? Please test and let me know

**Comment by Void48** [comment]
Or if you VPN to United States you should see the new navbar (try other browser if you don't)

**Comment by yakisova41** [comment]
I was able to confirm the Material 3 design navbar when I set the region to United States, so I fixed it in v0.2.3.

**Comment by Void48** [comment]
thank you for the fix ❤️ @yakisova41
